In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("Instagram_data_by_Bhanu.csv", encoding="latin1")

In [5]:
df.head()

,Impressions,From Home,From Hashtags,From Explore,From Other,Saves,Comments,Shares,Likes,Profile Visits,Follows,Caption,Hashtags
0,3920,2586,1028,619,56,98,9,5,162,35,2,Here are some of the most important data visua...,#finance #money #business #investing #investme...
1,5394,2727,1838,1174,78,194,7,14,224,48,10,Here are some of the best data science project...,#healthcare #health #covid #data #datascience ...
2,4021,2085,1188,0,533,41,11,1,131,62,12,Learn how to train a machine learning model an...,#data #datascience #dataanalysis #dataanalytic...
3,4528,2700,621,932,73,172,10,7,213,23,8,Heres how you can write a Python program to d...,#python #pythonprogramming #pythonprojects #py...
4,2518,1704,255,279,37,96,5,4,123,8,0,Plotting annotations while visualizing your da...,#datavisualization #datascience #data #dataana...

In [6]:
df.columns

Index(['Impressions', 'From Home', 'From Hashtags', 'From Explore',
       'From Other', 'Saves', 'Comments', 'Shares', 'Likes', 'Profile Visits',
       'Follows', 'Caption', 'Hashtags'],
      dtype='object')

In [7]:
df['Reach'] = df['Impressions']

In [8]:
data = df[['Reach','Likes', 'Comments', 'Shares', 'Saves', 'Impressions']]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Impressions     119 non-null    int64
 1   From Home       119 non-null    int64
 2   From Hashtags   119 non-null    int64
 3   From Explore    119 non-null    int64
 4   From Other      119 non-null    int64
 5   Saves           119 non-null    int64
 6   Comments        119 non-null    int64
 7   Shares          119 non-null    int64
 8   Likes           119 non-null    int64
 9   Profile Visits  119 non-null    int64
 10  Follows         119 non-null    int64
 11  Caption         119 non-null    object
 12  Hashtags        119 non-null    object
 13  Reach           119 non-null    int64
dtypes: int64(12), object(2)
memory usage: 13.1+ KB

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Reach        119 non-null    int64
 1   Likes        119 non-null    int64
 2   Comments     119 non-null    int64
 3   Shares       119 non-null    int64
 4   Saves        119 non-null    int64
 5   Impressions  119 non-null    int64
dtypes: int64(6)
memory usage: 5.7 KB

In [11]:
data.describe()

,Reach,Likes,Comments,Shares,Saves,Impressions
count,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000
mean,5703.991597,173.781513,6.663866,9.361345,153.310924,5703.991597
std,4843.780105,82.378947,3.544576,10.089205,156.317731,4843.780105
min,1941.000000,72.000000,0.000000,0.000000,22.000000,1941.000000
25%,3467.000000,121.500000,4.000000,3.000000,65.000000,3467.000000
50%,4289.000000,151.000000,6.000000,6.000000,109.000000,4289.000000
75%,6138.000000,204.000000,8.000000,13.500000,169.000000,6138.000000
max,36919.000000,549.000000,19.000000,75.000000,1095.000000,36919.000000

In [12]:
## Correlation
corr = data.corr()
corr

                Reach     Likes  Comments    Shares     Saves  Impressions
Reach        1.000000  0.849835 -0.028524  0.634675  0.779231     1.000000
Likes        0.849835  1.000000  0.123586  0.707794  0.845643     0.849835
Comments    -0.028524  0.123586  1.000000  0.016933 -0.026912    -0.028524
Shares       0.634675  0.707794  0.016933  1.000000  0.860324     0.634675
Saves        0.779231  0.845643 -0.026912  0.860324  1.000000     0.779231
Impressions  1.000000  0.849835 -0.028524  0.634675  0.779231     1.000000

In [13]:
## Simple Linear Regression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [37]:
X = data[['Likes']]
y = data['Impressions']

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [38]:
simple_model = LinearRegression()
simple_model.fit(X_train,y_train)

LinearRegression()

In [39]:
print("Slope:", simple_model.coef_[0])
print("Intercept:", simple_model.intercept_)

Slope: 47.71358944237497
Intercept: -2599.23008691457

In [40]:
y_pred = simple_model.predict(X_test)

In [41]:
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MSE:", mse)
print("MAE:", mae)
print("RMSE:", rmse)
print("R²:", r2)

MSE: 6460729.201708357
MAE: 1753.2068844049493
RMSE: 2541.7964516672764
R²: 0.8336482033976756

In [19]:
## Impression Prediction for 5000 Likes
print("Predicted Inpression for 5000 Likes:",simple_model.predict([[5000]])[0])

Predicted Inpression for 5000 Likes: 235968.71712496024

C:\ProgramData\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [20]:
# Scatter + regression line for simple LR
plt.scatter(X_test, y_test,color='blue', label='actual')
plt.plot(X_test, y_pred, linewidth=2, color='red', label='predicted')
plt.xlabel("Likes")
plt.ylabel("Impressions")
plt.title("Likes vs Impression with Regression Line")
plt.legend()
plt.show()

NameError: name 'plt' is not defined

In [ ]:
##Multiple Linear Regression
X_multi = data[['Likes', 'Comments', 'Shares', 'Saves', 'Impressions']]
y = data['Reach']

In [ ]:
X_train_m,X_test_m,y_train_m,y_test_m = train_test_split(X_multi, y, test_size=0.2, random_state=42)

In [ ]:
model_multi = LinearRegression()
model_multi.fit(X_train_m,y_train_m)

In [ ]:
print("Coefficients:", model_multi.coef_)
print("Intercept:", model_multi.intercept_)

In [ ]:
y_pred_m = model_multi.predict(X_test_m)

print("R² (multiple):", r2_score(y_test_m, y_pred_m))

In [ ]:
## We are Now predicting the reach of new post
new_post = pd.DataFrame({'Likes': [150], 'Comments': [20], 'Shares': [5], 'Saves': [10], 'Impressions': [5000]})

In [ ]:
predicted_reach = model_multi.predict(new_post)
#Or predicted_reach = model_multi.predict(X_multi)
print("Predicted Reach:", predicted_reach[0])

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
## Visualization
#simple Regression Scatter
plt.figure(figsize=(20,20))
plt.scatter(X_test,y_test)
plt.plot(X_test,y_test)
plt.title("Likes vs Reach with Regression Line")
plt.xlabel("Likes")
plt.ylabel("Reach")

plt.show()

In [ ]:
# Residuals (Error)
residuals = y_test - y_pred
plt.scatter(y_pred, residuals)
plt.axhline(0)
plt.title("Residual Plot")
plt.xlabel("Predicted Reach")
plt.ylabel("Residuals")
plt.show()

In [ ]:
##Regularization
from sklearn.linear_model import Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor

In [ ]:
ridge = Ridge(alpha=1.0).fit(X_train_m,y_train_m)
lasso = Lasso(alpha=0.1).fit(X_train_m,y_train_m)

In [ ]:
rf = RandomForestRegressor(n_estimators=300).fit(X_train_m,y_train_m)

In [ ]:
print("Ridge R²:", ridge.score(X_test_m, y_test_m))
print("Lasso R²:", lasso.score(X_test_m, y_test_m))
print("Random Forest R²:", rf.score(X_test_m, y_test_m))

In [ ]:
# Scatter + regression line for simple LR
plt.scatter(X_test, y_test)
plt.plot(X_test, y_pred, linewidth=2)
plt.xlabel("Likes")
plt.ylabel("Views")
plt.title("Likes vs Views with Regression Line")
plt.show()