In [2]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [3]:
df = pd.read_csv("ecommerce_transactions.csv")

In [4]:
df.head()

                       Items
0   Laptop, Mouse, USB Cable
1  Laptop, Laptop Bag, Mouse
2  Laptop, Laptop Bag, Mouse
3  Laptop, Laptop Bag, Mouse
4         Laptop, Laptop Bag

In [5]:
# Convert items into list
transactions = df['Items'].apply(lambda x: x.split(', ')).tolist()

In [6]:
transactions

[['Laptop', 'Mouse', 'USB Cable'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Headphones', 'Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop Bag'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Mouse'],
 ['Headphones', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag'],
 ['USB Cable'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse', 'USB Cable'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Mouse'],
 ['Keyboard'],
 ['Headphones', 'Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag'],
 ['Headphones', 'Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'USB Cable'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse', 'USB Cable'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Headphones'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['USB Cable'],
 ['Laptop', 'Laptop Bag'],
 ['Headphones', 'Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard'],
 ['Keyboard', 'Laptop', 'Laptop Bag'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Keyboard', 'Laptop Bag'],
 ['Keyboard'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'USB Cable'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Laptop', 'Mouse', 'USB Cable'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Headphones', 'Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop Bag'],
 ['Laptop', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag'],
 ['Headphones', 'Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop Bag'],
 ['Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Mouse'],
 ['Laptop', 'Mouse'],
 ['Keyboard'],
 ['Keyboard', 'USB Cable'],
 ['Laptop', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'USB Cable'],
 ['Laptop', 'Laptop Bag'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Mouse', 'USB Cable'],
 ['Headphones'],
 ['Laptop Bag'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse', 'USB Cable'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Mouse', 'USB Cable'],
 ['Headphones'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Mouse'],
 ['Laptop Bag'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'USB Cable'],
 ['Headphones'],
 ['Keyboard', 'Laptop', 'Mouse'],
 ['Laptop', 'Mouse', 'USB Cable'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'USB Cable'],
 ['Keyboard', 'Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Mouse'],
 ['Keyboard', 'Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'USB Cable'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'USB Cable'],
 ['Keyboard', 'Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['USB Cable'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Headphones', 'Keyboard', 'Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'USB Cable'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Mouse', 'USB Cable'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag'],
 ['Keyboard'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Headphones', 'Keyboard'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'USB Cable'],
 ['Laptop', 'Laptop Bag'],
 ['Keyboard', 'Laptop Bag', 'USB Cable'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'USB Cable'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Mouse', 'USB Cable'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse', 'USB Cable'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Mouse', 'USB Cable'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'USB Cable'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard'],
 ['Headphones', 'Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'USB Cable'],
 ['Laptop'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard'],
 ['Headphones', 'Laptop', 'Mouse'],
 ['Headphones', 'Laptop', 'Mouse'],
 ['Laptop', 'Mouse', 'USB Cable'],
 ['Laptop Bag'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Headphones', 'Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'USB Cable'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Keyboard', 'Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Mouse'],
 ['Mouse'],
 ['USB Cable'],
 ['Headphones'],
 ['Laptop', 'Laptop Bag', 'USB Cable'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'USB Cable'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'USB Cable'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Keyboard', 'Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Keyboard', 'Laptop', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag'],
 ['Headphones', 'Laptop', 'Laptop Bag'],
 ['Headphones', 'Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Laptop Bag', 'USB Cable'],
 ['Laptop'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop Bag'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Mouse', 'USB Cable'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Headphones'],
 ['Keyboard', 'Laptop', 'Mouse'],
 ['Laptop'],
 ['Laptop', 'Mouse', 'USB Cable'],
 ['Headphones'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Laptop', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop'],
 ['Headphones'],
 ['Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'USB Cable'],
 ['Headphones', 'Laptop'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Mouse'],
 ['Mouse'],
 ['Laptop', 'Mouse'],
 ['Headphones'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Mouse', 'USB Cable'],
 ['Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Laptop', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'USB Cable'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Headphones', 'Keyboard', 'Laptop', 'Laptop Bag'],
 ['Laptop', 'Mouse', 'USB Cable'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag'],
 ['Keyboard', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Keyboard', 'Laptop Bag', 'USB Cable'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Keyboard', 'Laptop', 'Mouse'],
 ['Laptop Bag', 'USB Cable'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Laptop', 'Mouse', 'USB Cable'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['USB Cable'],
 ['Keyboard'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'USB Cable'],
 ['Mouse'],
 ['Laptop', 'Mouse', 'USB Cable'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Keyboard'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Mouse', 'USB Cable'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse', 'USB Cable'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop'],
 ['Keyboard', 'Laptop', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Laptop'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'USB Cable'],
 ['Laptop', 'Mouse', 'USB Cable'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop Bag'],
 ['Laptop', 'Mouse'],
 ['Headphones'],
 ['Laptop', 'USB Cable'],
 ['Laptop'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'USB Cable'],
 ['Headphones'],
 ['Keyboard'],
 ['Laptop'],
 ['Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Headphones', 'Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'USB Cable'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag'],
 ['Keyboard'],
 ['USB Cable'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag'],
 ['Laptop', 'Mouse', 'USB Cable'],
 ['Headphones', 'Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Mouse', 'USB Cable'],
 ['Laptop Bag'],
 ['Headphones', 'Laptop', 'Mouse', 'USB Cable'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['USB Cable'],
 ['Laptop', 'Laptop Bag'],
 ['Headphones'],
 ['Laptop', 'Laptop Bag'],
 ['Keyboard', 'Laptop', 'Mouse'],
 ['Mouse', 'USB Cable'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag'],
 ['Headphones'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'USB Cable'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Mouse'],
 ['Keyboard', 'Laptop', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Keyboard', 'Laptop', 'Mouse', 'USB Cable'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag'],
 ['Mouse'],
 ['Headphones', 'Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Headphones', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop Bag'],
 ['Headphones'],
 ['Keyboard'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Mouse'],
 ['Keyboard', 'Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Laptop', 'Mouse'],
 ['Laptop Bag'],
 ['Keyboard'],
 ['Keyboard'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Mouse'],
 ['Headphones', 'Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Keyboard', 'Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Laptop Bag'],
 ['Laptop', 'Mouse'],
 ['Laptop', 'Laptop Bag', 'Mouse', 'USB Cable'],
 ['Headphones', 'Laptop', 'Mouse', 'USB Cable'],
 ['Laptop', 'Mouse', 'USB Cable'],

In [7]:
# One-hot encoding
te = TransactionEncoder()
te_array = te.fit(transactions).transform(transactions)
df_encoded = pd.DataFrame(te_array, columns=te.columns_)

In [8]:
df_encoded

     Headphones  Keyboard  Laptop  Laptop Bag  Mouse  USB Cable
0         False     False    True       False   True       True
1         False     False    True        True   True      False
2         False     False    True        True   True      False
3         False     False    True        True   True      False
4         False     False    True        True  False      False
..          ...       ...     ...         ...    ...        ...
995       False      True    True        True  False       True
996       False     False    True        True   True       True
997       False     False    True        True   True      False
998       False     False    True        True  False      False
999       False     False    True        True   True      False

[1000 rows x 6 columns]

In [9]:
# Apply Apriori
frequent_itemsets = apriori(df_encoded, min_support=0.4, use_colnames=True)

In [10]:
frequent_itemsets

   support                     itemsets
0    0.871                     (Laptop)
1    0.655                 (Laptop Bag)
2    0.669                      (Mouse)
3    0.623         (Laptop Bag, Laptop)
4    0.638              (Mouse, Laptop)
5    0.419          (Mouse, Laptop Bag)
6    0.416  (Mouse, Laptop Bag, Laptop)

In [11]:
# Generate rules
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=0.6)

In [12]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Laptop Bag),(Laptop),0.655,0.871,0.623,0.951145,1.092015,1.0,0.052495,2.640469,0.244237,0.689922,0.621279,0.833207
1,(Laptop),(Laptop Bag),0.871,0.655,0.623,0.715270,1.092015,1.0,0.052495,1.211673,0.653191,0.689922,0.174695,0.833207
2,(Mouse),(Laptop),0.669,0.871,0.638,0.953662,1.094905,1.0,0.055301,2.783903,0.261869,0.707317,0.640792,0.843077
3,(Laptop),(Mouse),0.871,0.669,0.638,0.732491,1.094905,1.0,0.055301,1.237343,0.671928,0.707317,0.191817,0.843077
4,(Laptop Bag),(Mouse),0.655,0.669,0.419,0.639695,0.956195,1.0,-0.019195,0.918665,-0.117221,0.462983,-0.088536,0.633001
5,(Mouse),(Laptop Bag),0.669,0.655,0.419,0.626308,0.956195,1.0,-0.019195,0.923220,-0.121577,0.462983,-0.083165,0.633001
6,"(Mouse, Laptop Bag)",(Laptop),0.419,0.871,0.416,0.992840,1.139885,1.0,0.051051,18.017000,0.211220,0.475973,0.944497,0.735226
7,"(Laptop Bag, Laptop)",(Mouse),0.623,0.669,0.416,0.667737,0.998112,1.0,-0.000787,0.996198,-0.004993,0.474886,-0.003816,0.644780
8,"(Mouse, Laptop)",(Laptop Bag),0.638,0.655,0.416,0.652038,0.995477,1.0,-0.001890,0.991486,-0.012395,0.474344,-0.008587,0.643576
9,(Laptop Bag),"(Mouse, Laptop)",0.655,0.638,0.416,0.635115,0.995477,1.0,-0.001890,0.992092,-0.012998,0.474344,-0.007971,0.643576
10,(Mouse),"(Laptop Bag, Laptop)",0.669,0.623,0.416,0.621824,0.998112,1.0,-0.000787,0.996889,-0.005683,0.474886,-0.003120,0.644780
11,(Laptop),"(Mouse, Laptop Bag)",0.871,0.419,0.416,0.477612,1.139885,1.0,0.051051,1.112200,0.951308,0.475973,0.100881,0.735226