In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [3]:
df = pd.read_csv("finance_transactions.csv")
df.head()

                     Items
0          Online Shopping
1          Online Shopping
2  Online Shopping, Travel
3          Online Shopping
4                   Dining

In [4]:
#converting into list
t = df['Items'].apply(lambda x: x.split(', ')).tolist()

In [5]:
#one hot encoding
te = TransactionEncoder()
te_arr = te.fit(t).transform(t)
df_encoded = pd.DataFrame(te_arr, columns = te.columns_)

In [6]:
#apply apriori
freq = apriori(df_encoded, min_support=0.2, use_colnames=True)

In [7]:
freq

   support                   itemsets
0    0.699          (Online Shopping)
1    0.701                   (Travel)
2    0.615  (Travel, Online Shopping)

In [8]:
#Gnerate Rules
rules = association_rules(freq, metric='confidence', min_threshold=0.4)

In [9]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Travel),(Online Shopping),0.701,0.699,0.615,0.877318,1.255105,1.0,0.125001,2.453500,0.679778,0.783439,0.592419,0.878573
1,(Online Shopping),(Travel),0.699,0.701,0.615,0.879828,1.255105,1.0,0.125001,2.488107,0.675261,0.783439,0.598088,0.878573