In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [5]:
df = pd.read_csv("food_delivery_transactions.csv")
df.head()

                     Items
0  Burger, Coke, Ice Cream
1      Burger, Coke, Fries
2      Burger, Coke, Fries
3                Ice Cream
4             Burger, Coke

In [8]:
#converting into list
t = df['Items'].apply(lambda x: x.split(', ')).tolist()

In [11]:
#one hot encoding
te = TransactionEncoder()
te_arr = te.fit(t).transform(t)
df_encoded = pd.DataFrame(te_arr, columns = te.columns_)

In [13]:
#apply apriori
freq = apriori(df_encoded, min_support=0.4, use_colnames=True)

In [17]:
freq

   support               itemsets
0    0.884               (Burger)
1    0.680                 (Coke)
2    0.677                (Fries)
3    0.640         (Coke, Burger)
4    0.644        (Fries, Burger)
5    0.429          (Fries, Coke)
6    0.428  (Fries, Coke, Burger)

In [18]:
#Gnerate Rules
rules = association_rules(freq, metric='confidence', min_threshold=0.6)

In [19]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Burger),(Coke),0.884,0.680,0.640,0.723982,1.064679,1.0,0.038880,1.159344,0.523707,0.692641,0.137443,0.832579
1,(Coke),(Burger),0.680,0.884,0.640,0.941176,1.064679,1.0,0.038880,1.972000,0.189844,0.692641,0.492901,0.832579
2,(Fries),(Burger),0.677,0.884,0.644,0.951256,1.076081,1.0,0.045532,2.379758,0.218891,0.702290,0.579789,0.839881
3,(Burger),(Fries),0.884,0.677,0.644,0.728507,1.076081,1.0,0.045532,1.189717,0.609499,0.702290,0.159464,0.839881
4,(Fries),(Coke),0.677,0.680,0.429,0.633678,0.931879,1.0,-0.031360,0.873548,-0.184550,0.462284,-0.144756,0.632280
5,(Coke),(Fries),0.680,0.677,0.429,0.630882,0.931879,1.0,-0.031360,0.875060,-0.185958,0.462284,-0.142779,0.632280
6,"(Fries, Burger)",(Coke),0.644,0.680,0.428,0.664596,0.977347,1.0,-0.009920,0.954074,-0.061126,0.477679,-0.048137,0.647004
7,"(Fries, Coke)",(Burger),0.429,0.884,0.428,0.997669,1.128585,1.0,0.048764,49.764000,0.199535,0.483616,0.979905,0.740916
8,"(Coke, Burger)",(Fries),0.640,0.677,0.428,0.668750,0.987814,1.0,-0.005280,0.975094,-0.033133,0.481440,-0.025542,0.650475
9,(Fries),"(Coke, Burger)",0.677,0.640,0.428,0.632201,0.987814,1.0,-0.005280,0.978795,-0.036788,0.481440,-0.021664,0.650475
10,(Coke),"(Fries, Burger)",0.680,0.644,0.428,0.629412,0.977347,1.0,-0.009920,0.960635,-0.067538,0.477679,-0.040978,0.647004